project:
  type: website
  render:
    - "*.{qmd,ipynb,rmd,md}"
    - "!webr_packages/"
    - "!data/"
  resources:
    - "images/*"
    - "images/abstracts/*"
    - "images/news/*"
    - "data/wasm/*"
    - "data/wasm/samples/project-demo-datadir.data/content"
    - "data/wasm/samples/project-demo-datadir.js.metadata/content"
    - "data/wasm/samples/project-demo-fsaverage.data/content"
    - "data/wasm/samples/project-demo-fsaverage.js.metadata/content"
    - "data/wasm/samples/project-demo-mni152.data/content"
    - "data/wasm/samples/project-demo-mni152.js.metadata/content"
    - "data/wasm/samples/project-demo-n27.data/content"
    - "data/wasm/samples/project-demo-n27.js.metadata/content"
    - "data/wasm/samples/project-demo-rawdir.data/content"
    - "data/wasm/samples/project-demo-rawdir.js.metadata/content"
    - "favicon.ico"

website:
  title: "RAVE"
  favicon: favicon.ico
  repo-url: https://github.com/rave-ieeg/rave-ieeg.github.io
  repo-actions: [edit, source, issue]
  repo-link-target: "_blank"
  navbar:
    background: "#000000"
    left:
      - href: index.qmd
        text: Home
      - href: posts/3dviewer/viewer301.html?viewer=full
        text: Demo
      - href: blogs.md
        text: Documentation
      - href: https://github.com/orgs/rave-ieeg/discussions
        text: Help & Discussion
        target: "_blank"
    tools:
      - icon: github
        href: https://github.com/rave-ieeg/
        target: "_blank"
        size: 3
  sidebar: false
  page-footer:
    left: "Credit [Zhengjia Wang](https://dipterix.org){target='_blank'} for creating the website."
    center: "{{< fa regular copyright >}} Copyright 2024, [BeauchampLab](https://beauchamplab.med.upenn.edu){target='_blank'}."
    right: "[Guide to edit this website](https://rave.wiki/posts/editor-notes/how-to-edit-this-website.html){target='_blank'}"
    border: true
  google-analytics:
    tracking-id: GTM-MVX9KRN9
    anonymize-ip: true

format:
  html:
    theme:
      - zephyr
      - css/styles.scss
    toc: true
    page-layout: full
include-in-header:
  text: <script type="text/javascript" type="module" src="/js/customize.js"></script>

editor: visual

