on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Additional System Libraries on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y \
            libhdf5-dev python3 git libcurl4-openssl-dev libssl-dev \
            libfftw3-dev make libgit2-dev libhdf5-dev zlib1g-dev libglpk-dev \
            libxml2-dev pandoc cmake libzmq3-dev libpng-dev libfreetype6-dev \
            libjpeg-dev libtiff-dev libicu-dev libfontconfig1-dev \
            libfribidi-dev libharfbuzz-dev \
            pkg-config

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
